2026-01-09 14:50:22 - INFO - rt2ms program starting
2026-01-09 14:50:22 - DEBUG - ['/home/gabrielgoes/TMP/SYNC/python/rt2ms_py3/rt2ms_py3/rt2ms_py3.py', '-d', '/home/gabrielgoes/TMP/SYNC/BC9_20251211/BC9_20251211_BINARIES', '-e'] - v2023.4.2.0 - Python:3.7.3 (default, Mar 23 2024, 16:12:05) 
[GCC 8.3.0]
2026-01-09 14:50:22 - DEBUG - CWD: /var/WORKTMP/SYNC/BC9_20251211
2026-01-09 14:50:22 - INFO - Version: 2023.4.2.0
2026-01-09 14:50:22 - INFO - Generating parameter file using rt2ms in 'exploratory mode'!
2026-01-09 14:50:22 - INFO - Gathering parfile information for cf_card_dir: '/home/gabrielgoes/TMP/SYNC/BC9_20251211/BC9_20251211_BINARIES'
2026-01-09 14:50:23 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 14:50:23 - INFO - Invalid channel name found contv. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HHZ. Please, make sure this is correct!
2026-01-09 14:50:23 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 14:50:23 - INFO - Invalid channel name found contns. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HH1. Please, make sure this is correct!
2026-01-09 14:50:23 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 14:50:23 - INFO - Invalid channel name found contew. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HH2. Please, make sure this is correct!
2026-01-09 14:50:23 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 14:50:23 - INFO - Invalid channel name found regv. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HHZ. Please, make sure this is correct!
2026-01-09 14:50:23 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 14:50:23 - INFO - Invalid channel name found regns. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HH1. Please, make sure this is correct!
2026-01-09 14:50:23 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 14:50:23 - INFO - Invalid channel name found regew. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HH2. Please, make sure this is correct!
2026-01-09 14:50:23 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 14:50:23 - INFO - Invalid channel name found locv. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HHZ. Please, make sure this is correct!
2026-01-09 14:50:23 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 14:50:23 - INFO - Invalid channel name found locns. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HH1. Please, make sure this is correct!
2026-01-09 14:50:23 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 14:50:23 - INFO - Invalid channel name found locew. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HH2. Please, make sure this is correct!
2026-01-09 14:50:23 - INFO - Writing parameter file in dir: '/var/WORKTMP/SYNC/BC9_20251211' 
2026-01-09 14:50:23 - INFO - Parameter file:
das; refchan; refstrm; netcode; station; location; channel; samplerate; gain; implement_time
9690; 1; 1; XX; bc9; ; HHZ; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 2; 1; XX; bc9; ; HH1; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 3; 1; XX; bc9; ; HH2; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 1; 2; XX; bc9; ; HHZ; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 2; 2; XX; bc9; ; HH1; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 3; 2; XX; bc9; ; HH2; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 1; 3; XX; bc9; ; HHZ; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 2; 3; XX; bc9; ; HH1; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 3; 3; XX; bc9; ; HH2; 100; 1; 2016-06-23T16:55:40.000000Z
2026-01-09 14:50:23 - WARNING - !!! Review and if necessary edit the generated parameter file before running rt2ms in 'conversion' mode !!!
2026-01-09 14:50:24 - INFO - rt2ms program starting
2026-01-09 14:50:24 - DEBUG - ['/home/gabrielgoes/TMP/SYNC/python/rt2ms_py3/rt2ms_py3/rt2ms_py3.py', '-d', '/home/gabrielgoes/TMP/SYNC/BC9_20251211/BC9_20251211_BINARIES', '-p', '/home/gabrielgoes/TMP/SYNC/PARFILES//BC9_parfile.txt', '-o', 'BC.BC9.MSEED'] - v2023.4.2.0 - Python:3.7.3 (default, Mar 23 2024, 16:12:05) 
[GCC 8.3.0]
2026-01-09 14:50:24 - DEBUG - CWD: /var/WORKTMP/SYNC/BC9_20251211
2026-01-09 14:50:24 - INFO - Version: 2023.4.2.0
2026-01-09 14:50:24 - ERROR - This parameter file '/home/gabrielgoes/TMP/SYNC/PARFILES//BC9_parfile.txt' does not exist!
2026-01-09 17:39:20 - INFO - rt2ms program starting
2026-01-09 17:39:20 - DEBUG - ['/home/gabrielgoes/TMP/SYNC/python/rt2ms_py3/rt2ms_py3/rt2ms_py3.py', '-d', '/home/gabrielgoes/TMP/SYNC/BC9_20251211/BC9_20251211_BINARIES', '-e'] - v2023.4.2.0 - Python:3.7.3 (default, Mar 23 2024, 16:12:05) 
[GCC 8.3.0]
2026-01-09 17:39:20 - DEBUG - CWD: /var/WORKTMP/SYNC/BC9_20251211
2026-01-09 17:39:20 - INFO - Version: 2023.4.2.0
2026-01-09 17:39:20 - INFO - Generating parameter file using rt2ms in 'exploratory mode'!
2026-01-09 17:39:20 - INFO - Gathering parfile information for cf_card_dir: '/home/gabrielgoes/TMP/SYNC/BC9_20251211/BC9_20251211_BINARIES'
2026-01-09 17:39:21 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 17:39:21 - INFO - Invalid channel name found contv. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HHZ. Please, make sure this is correct!
2026-01-09 17:39:21 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 17:39:21 - INFO - Invalid channel name found contns. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HH1. Please, make sure this is correct!
2026-01-09 17:39:21 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 17:39:21 - INFO - Invalid channel name found contew. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HH2. Please, make sure this is correct!
2026-01-09 17:39:21 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 17:39:21 - INFO - Invalid channel name found regv. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HHZ. Please, make sure this is correct!
2026-01-09 17:39:21 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 17:39:21 - INFO - Invalid channel name found regns. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HH1. Please, make sure this is correct!
2026-01-09 17:39:21 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 17:39:21 - INFO - Invalid channel name found regew. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HH2. Please, make sure this is correct!
2026-01-09 17:39:21 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 17:39:21 - INFO - Invalid channel name found locv. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HHZ. Please, make sure this is correct!
2026-01-09 17:39:21 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 17:39:21 - INFO - Invalid channel name found locns. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HH1. Please, make sure this is correct!
2026-01-09 17:39:21 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 17:39:21 - INFO - Invalid channel name found locew. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HH2. Please, make sure this is correct!
2026-01-09 17:39:21 - INFO - Writing parameter file in dir: '/var/WORKTMP/SYNC/BC9_20251211' 
2026-01-09 17:39:21 - INFO - Parameter file:
das; refchan; refstrm; netcode; station; location; channel; samplerate; gain; implement_time
9690; 1; 1; XX; bc9; ; HHZ; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 2; 1; XX; bc9; ; HH1; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 3; 1; XX; bc9; ; HH2; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 1; 2; XX; bc9; ; HHZ; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 2; 2; XX; bc9; ; HH1; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 3; 2; XX; bc9; ; HH2; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 1; 3; XX; bc9; ; HHZ; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 2; 3; XX; bc9; ; HH1; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 3; 3; XX; bc9; ; HH2; 100; 1; 2016-06-23T16:55:40.000000Z
2026-01-09 17:39:21 - WARNING - !!! Review and if necessary edit the generated parameter file before running rt2ms in 'conversion' mode !!!
2026-01-09 17:39:22 - INFO - rt2ms program starting
2026-01-09 17:39:22 - DEBUG - ['/home/gabrielgoes/TMP/SYNC/python/rt2ms_py3/rt2ms_py3/rt2ms_py3.py', '-d', '/home/gabrielgoes/TMP/SYNC/BC9_20251211/BC9_20251211_BINARIES', '-X'] - v2023.4.2.0 - Python:3.7.3 (default, Mar 23 2024, 16:12:05) 
[GCC 8.3.0]
2026-01-09 17:39:22 - DEBUG - CWD: /var/WORKTMP/SYNC/BC9_20251211
2026-01-09 17:39:22 - INFO - Version: 2023.4.2.0
2026-01-09 17:39:22 - INFO - Running rt2ms in troubleshooting mode
2026-01-09 17:39:22 - INFO - Working on CF card directory: /home/gabrielgoes/TMP/SYNC/BC9_20251211/BC9_20251211_BINARIES
2026-01-09 17:39:22 - INFO - Parsing and writing state of health information for datalogger number: 9690
2026-01-09 17:39:23 - INFO - Parsing and writing state of health information for rt130 files: 100/1724
2026-01-09 17:39:24 - INFO - Parsing and writing state of health information for rt130 files: 200/1724
2026-01-09 17:39:25 - INFO - Parsing and writing state of health information for rt130 files: 300/1724
2026-01-09 17:39:26 - INFO - Parsing and writing state of health information for rt130 files: 400/1724
2026-01-09 17:39:27 - INFO - Parsing and writing state of health information for rt130 files: 500/1724
2026-01-09 17:39:28 - INFO - Parsing and writing state of health information for rt130 files: 600/1724
2026-01-09 17:39:28 - INFO - Parsing and writing state of health information for rt130 files: 700/1724
2026-01-09 17:39:29 - INFO - Parsing and writing state of health information for rt130 files: 800/1724
2026-01-09 17:39:30 - INFO - Parsing and writing state of health information for rt130 files: 900/1724
2026-01-09 17:39:31 - INFO - Parsing and writing state of health information for rt130 files: 1000/1724
2026-01-09 17:39:32 - INFO - Parsing and writing state of health information for rt130 files: 1100/1724
2026-01-09 17:39:33 - INFO - Parsing and writing state of health information for rt130 files: 1200/1724
2026-01-09 17:39:34 - INFO - Parsing and writing state of health information for rt130 files: 1300/1724
2026-01-09 17:39:35 - INFO - Parsing and writing state of health information for rt130 files: 1400/1724
2026-01-09 17:39:36 - INFO - Parsing and writing state of health information for rt130 files: 1500/1724
2026-01-09 17:39:37 - INFO - Parsing and writing state of health information for rt130 files: 1600/1724
2026-01-09 17:39:38 - INFO - Parsing and writing state of health information for rt130 files: 1700/1724
2026-01-09 17:39:41 - INFO - rt2ms ran for 19.047093391418457 s
