2026-01-09 18:30:59 - INFO - rt2ms program starting
2026-01-09 18:30:59 - DEBUG - ['/home/gabrielgoes/TMP/SYNC/python/rt2ms_py3/rt2ms_py3/rt2ms_py3.py', '-d', '/home/gabrielgoes/TMP/SYNC/BC9_20251211/BC9_20251211_BINARIES', '-e'] - v2023.4.2.0 - Python:3.7.3 (default, Mar 23 2024, 16:12:05) 
[GCC 8.3.0]
2026-01-09 18:30:59 - DEBUG - CWD: /var/WORKTMP/SYNC/BC9_20251211
2026-01-09 18:30:59 - INFO - Version: 2023.4.2.0
2026-01-09 18:30:59 - INFO - Generating parameter file using rt2ms in 'exploratory mode'!
2026-01-09 18:30:59 - INFO - Gathering parfile information for cf_card_dir: '/home/gabrielgoes/TMP/SYNC/BC9_20251211/BC9_20251211_BINARIES'
2026-01-09 18:30:59 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 18:30:59 - INFO - Invalid channel name found contv. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HHZ. Please, make sure this is correct!
2026-01-09 18:30:59 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 18:30:59 - INFO - Invalid channel name found contns. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HH1. Please, make sure this is correct!
2026-01-09 18:30:59 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 18:30:59 - INFO - Invalid channel name found contew. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HH2. Please, make sure this is correct!
2026-01-09 18:30:59 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 18:30:59 - INFO - Invalid channel name found regv. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HHZ. Please, make sure this is correct!
2026-01-09 18:30:59 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 18:30:59 - INFO - Invalid channel name found regns. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HH1. Please, make sure this is correct!
2026-01-09 18:30:59 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 18:30:59 - INFO - Invalid channel name found regew. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HH2. Please, make sure this is correct!
2026-01-09 18:30:59 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 18:30:59 - INFO - Invalid channel name found locv. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HHZ. Please, make sure this is correct!
2026-01-09 18:30:59 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 18:30:59 - INFO - Invalid channel name found locns. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HH1. Please, make sure this is correct!
2026-01-09 18:30:59 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 18:30:59 - INFO - Invalid channel name found locew. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HH2. Please, make sure this is correct!
2026-01-09 18:30:59 - INFO - Writing parameter file in dir: '/var/WORKTMP/SYNC/BC9_20251211' 
2026-01-09 18:30:59 - INFO - Parameter file:
das; refchan; refstrm; netcode; station; location; channel; samplerate; gain; implement_time
9690; 1; 1; XX; bc9; ; HHZ; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 2; 1; XX; bc9; ; HH1; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 3; 1; XX; bc9; ; HH2; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 1; 2; XX; bc9; ; HHZ; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 2; 2; XX; bc9; ; HH1; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 3; 2; XX; bc9; ; HH2; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 1; 3; XX; bc9; ; HHZ; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 2; 3; XX; bc9; ; HH1; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 3; 3; XX; bc9; ; HH2; 100; 1; 2016-06-23T16:55:40.000000Z
2026-01-09 18:30:59 - WARNING - !!! Review and if necessary edit the generated parameter file before running rt2ms in 'conversion' mode !!!
2026-01-09 18:31:01 - INFO - rt2ms program starting
2026-01-09 18:31:01 - DEBUG - ['/home/gabrielgoes/TMP/SYNC/python/rt2ms_py3/rt2ms_py3/rt2ms_py3.py', '-d', '/home/gabrielgoes/TMP/SYNC/BC9_20251211/BC9_20251211_BINARIES', '-X'] - v2023.4.2.0 - Python:3.7.3 (default, Mar 23 2024, 16:12:05) 
[GCC 8.3.0]
2026-01-09 18:31:01 - DEBUG - CWD: /var/WORKTMP/SYNC/BC9_20251211
2026-01-09 18:31:01 - INFO - Version: 2023.4.2.0
2026-01-09 18:31:01 - INFO - Running rt2ms in troubleshooting mode
2026-01-09 18:31:01 - INFO - Working on CF card directory: /home/gabrielgoes/TMP/SYNC/BC9_20251211/BC9_20251211_BINARIES
2026-01-09 18:31:01 - INFO - Parsing and writing state of health information for datalogger number: 9690
2026-01-09 18:31:02 - INFO - Parsing and writing state of health information for rt130 files: 100/1724
2026-01-09 18:31:03 - INFO - Parsing and writing state of health information for rt130 files: 200/1724
2026-01-09 18:31:03 - INFO - Parsing and writing state of health information for rt130 files: 300/1724
2026-01-09 18:31:04 - INFO - Parsing and writing state of health information for rt130 files: 400/1724
2026-01-09 18:31:05 - INFO - Parsing and writing state of health information for rt130 files: 500/1724
2026-01-09 18:31:06 - INFO - Parsing and writing state of health information for rt130 files: 600/1724
2026-01-09 18:31:06 - INFO - Parsing and writing state of health information for rt130 files: 700/1724
2026-01-09 18:31:07 - INFO - Parsing and writing state of health information for rt130 files: 800/1724
2026-01-09 18:31:08 - INFO - Parsing and writing state of health information for rt130 files: 900/1724
2026-01-09 18:31:08 - INFO - Parsing and writing state of health information for rt130 files: 1000/1724
2026-01-09 18:31:09 - INFO - Parsing and writing state of health information for rt130 files: 1100/1724
2026-01-09 18:31:10 - INFO - Parsing and writing state of health information for rt130 files: 1200/1724
2026-01-09 18:31:11 - INFO - Parsing and writing state of health information for rt130 files: 1300/1724
2026-01-09 18:31:12 - INFO - Parsing and writing state of health information for rt130 files: 1400/1724
2026-01-09 18:31:13 - INFO - Parsing and writing state of health information for rt130 files: 1500/1724
2026-01-09 18:31:14 - INFO - Parsing and writing state of health information for rt130 files: 1600/1724
2026-01-09 18:31:16 - INFO - Parsing and writing state of health information for rt130 files: 1700/1724
2026-01-09 18:31:18 - INFO - rt2ms ran for 17.965822458267212 s
