2026-01-09 14:50:22 - INFO - rt2ms program starting
2026-01-09 14:50:22 - DEBUG - ['/home/gabrielgoes/TMP/SYNC/python/rt2ms_py3/rt2ms_py3/rt2ms_py3.py', '-d', '/home/gabrielgoes/TMP/SYNC/BC9_20251211/BC9_20251211_BINARIES', '-e'] - v2023.4.2.0 - Python:3.7.3 (default, Mar 23 2024, 16:12:05) 
[GCC 8.3.0]
2026-01-09 14:50:22 - DEBUG - CWD: /var/WORKTMP/SYNC/BC9_20251211
2026-01-09 14:50:22 - INFO - Version: 2023.4.2.0
2026-01-09 14:50:22 - INFO - Generating parameter file using rt2ms in 'exploratory mode'!
2026-01-09 14:50:22 - INFO - Gathering parfile information for cf_card_dir: '/home/gabrielgoes/TMP/SYNC/BC9_20251211/BC9_20251211_BINARIES'
2026-01-09 14:50:23 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 14:50:23 - INFO - Invalid channel name found contv. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HHZ. Please, make sure this is correct!
2026-01-09 14:50:23 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 14:50:23 - INFO - Invalid channel name found contns. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HH1. Please, make sure this is correct!
2026-01-09 14:50:23 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 14:50:23 - INFO - Invalid channel name found contew. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HH2. Please, make sure this is correct!
2026-01-09 14:50:23 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 14:50:23 - INFO - Invalid channel name found regv. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HHZ. Please, make sure this is correct!
2026-01-09 14:50:23 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 14:50:23 - INFO - Invalid channel name found regns. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HH1. Please, make sure this is correct!
2026-01-09 14:50:23 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 14:50:23 - INFO - Invalid channel name found regew. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HH2. Please, make sure this is correct!
2026-01-09 14:50:23 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 14:50:23 - INFO - Invalid channel name found locv. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HHZ. Please, make sure this is correct!
2026-01-09 14:50:23 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 14:50:23 - INFO - Invalid channel name found locns. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HH1. Please, make sure this is correct!
2026-01-09 14:50:23 - INFO - Invalid network code (netcode = ). The network code should be two alphanumeric character long. Setting network code to default one (XX).
2026-01-09 14:50:23 - INFO - Invalid channel name found locew. Based on a sampling rate of 100 Hz and a gain of 1, renaming channel as HH2. Please, make sure this is correct!
2026-01-09 14:50:23 - INFO - Writing parameter file in dir: '/var/WORKTMP/SYNC/BC9_20251211' 
2026-01-09 14:50:23 - INFO - Parameter file:
das; refchan; refstrm; netcode; station; location; channel; samplerate; gain; implement_time
9690; 1; 1; XX; bc9; ; HHZ; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 2; 1; XX; bc9; ; HH1; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 3; 1; XX; bc9; ; HH2; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 1; 2; XX; bc9; ; HHZ; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 2; 2; XX; bc9; ; HH1; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 3; 2; XX; bc9; ; HH2; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 1; 3; XX; bc9; ; HHZ; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 2; 3; XX; bc9; ; HH1; 100; 1; 2016-06-23T16:55:40.000000Z
9690; 3; 3; XX; bc9; ; HH2; 100; 1; 2016-06-23T16:55:40.000000Z
2026-01-09 14:50:23 - WARNING - !!! Review and if necessary edit the generated parameter file before running rt2ms in 'conversion' mode !!!
2026-01-09 14:50:24 - INFO - rt2ms program starting
2026-01-09 14:50:24 - DEBUG - ['/home/gabrielgoes/TMP/SYNC/python/rt2ms_py3/rt2ms_py3/rt2ms_py3.py', '-d', '/home/gabrielgoes/TMP/SYNC/BC9_20251211/BC9_20251211_BINARIES', '-p', '/home/gabrielgoes/TMP/SYNC/PARFILES//BC9_parfile.txt', '-o', 'BC.BC9.MSEED'] - v2023.4.2.0 - Python:3.7.3 (default, Mar 23 2024, 16:12:05) 
[GCC 8.3.0]
2026-01-09 14:50:24 - DEBUG - CWD: /var/WORKTMP/SYNC/BC9_20251211
2026-01-09 14:50:24 - INFO - Version: 2023.4.2.0
2026-01-09 14:50:24 - ERROR - This parameter file '/home/gabrielgoes/TMP/SYNC/PARFILES//BC9_parfile.txt' does not exist!
